config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "contact",to: "pages#contact"
  get "about", to: "pages#about"
  get "error", to: "pages#error"

  get "blog",to: redirect("http://alimalik11512.blogspot.com/2015/01/register.html")
  
  resources :projects do
    resources :tasks, except: [:index]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pages#home"

  get "*path",to: redirect("/error")

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/counter.rb
class Counter
    def self.calculate_percent_complete(complete_task,total_task)
        complete_task.to_f/total_task.to_f * 100
    end
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tasks
    after_initialize :set_defaults

    validates_presence_of :title, :description
    scope :almost_complete,-> {where('percent_complete > 75')}
    scope :still_need_some_work,->{where('percent_complete <= 75')}

    def set_defaults
        self.percent_complete ||= 0.0 
    end
end

app/models/task.rb
class Task < ApplicationRecord
  #include ActionView::Helpers

  belongs_to :project

  after_save :update_percent_completed if :mark_completed?

  mount_uploader :task_file, TaskFileUploader

  def mark_completed?
    self.complted==true
  end

  scope :completed, -> {where(complted: true)}

  
  def update_percent_completed
    project = Project.find(self.project_id)
    count_of_completed_taks=project.tasks.completed.count
    count_of_total_tasks=project.tasks.count
    project.update(percent_complete: Counter.calculate_percent_complete(count_of_completed_taks,count_of_total_tasks))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def about
  end

  def home
    @projects=Project.all
  end

  def error 
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.still_need_some_work
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @tasks=@project.tasks
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :percent_complete)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: [:show, :edit,:new,:create, :update, :destroy]

  def show
    @task=@project.tasks.find(params[:id])
  end

  def new
    @task = @project.tasks.build
    respond_to do |format|
      format.html 
    end
  end

  def edit
    @task = @project.tasks.find(params[:id])
  end

  def create
    @task= @project.tasks.create(task_params)
    #@task.project_id=@project_id

    respond_to do |format|
      if @task.save
        format.html {redirect_to project_url(@task.project_id), notice: "Task was creted succesfully!"}
        format.json {render :show, status: :created, location: @task}
      else
        format.html {render :new}
        format.json {render json: @task.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    @task = @project.tasks.find(params[:id])
    respond_to do |format|
      if @task.update(task_params)
        format.html {redirect_to project_url(@task.project_id), notice: "Task was updated succesfully!"}
        format.json {render :show, status: :created, location: @task}
      else
        format.html {render :edit}
        format.json {render json: @task.errors, status: :unprocessable_entity}
      end 
    end
  end

  def destroy
    task=project.tasks.find(:project_id)
    @task.destroy
    respond_to dask.new(task_params) do |format|
      format.html {redirect_to Project_url(@task.project_id), notice: "Task was deleted succesfully!"}
      format.json {head :no_content}
    end
  end


  private

  def set_task
    task=Task.find(params[:id])
  end

  def set_project
    @project=Project.find(params[:project_id])
  end

  def task_params
    params.require(:task).permit(:title,:desciption,:project_id,:complted,:task_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def self.calculate_percent_complete(complete_task,total_task)
        complete_task.to_f/total_task.to_f * 100
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taski</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= image_tag("logo.png", width: '150px',:align=>"middle") %> 
  <br>


  <%= render 'shared/nav' %>
  <%= render 'shared/alerts'%>
  <%= link_to 'Projects', projects_path %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/error.html.erb
<h1>sorry this pages is not exist</h1>


Go Back To <%= link_to 'Home Page', root_path %>

app/views/pages/home.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Percent complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.percent_complete %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :percent_complete %>
    <%= form.text_field :percent_complete %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Percent complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.percent_complete %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Percent complete:</strong>
  <%= @project.percent_complete %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

<h2>Tasks for Projects</h2>

<% @tasks.each do |task| %>
  <%= link_to task.title , project_task_path(@project.id,task.id) %>
  <br>
  <br>
<% end %>
<br>
<%= link_to 'Add a New Task for this Project', new_project_task_path(project_id: @project.id) %>

app/views/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_nav.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Contact', contact_path %>
<%= link_to 'Blog', blog_path %>

<br>
<br>

<% if current_user %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <%= link_to 'Edit Account', edit_user_registration_path %>
<% else %>
  <%= link_to 'Register', new_user_registration_path %>
  <%= link_to 'Sign In', new_user_session_path %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_for([@task.project,@task]) do |f| %>
    <% if @task.errors.any? %>
        <%= pluralize(@task.errors.count, "error")%> Prohibited this project from being saved:
        <% @task.errors.full_messages.each do |message| %>
            <%= message%>
        <%end%>  
    <% end %>

    <%= f.label :title%>
    <%= f.text_field :title%>

    <%= f.label :desciption%>
    <%= f.text_area :desciption%>

    <%= f.label :complted%>
    <%= f.check_box :complted%>

    <%= f.label "Attachment"%>
    <%= f.file_field :task_file%>

    <div class="field">
    <%= f.hidden_field :project_id %>
    </div>

    <%= f.submit %>
<% end%>

<!--  url: project_tasks_path(@project)>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1>Tasks</h1>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.desciption %>
</p>



<p>
  <strong>Task complete:</strong>
  <%= @task.complted %>
</p>

<% unless @task.task_file.blank? %>
  <p><%= link_to 'Attachment', @task.task_file.to_s %></p>
<% end %>

<%= link_to 'Edit', edit_project_task_path(@task.project_id,@task.id) %>
<%= link_to 'Back to Project', project_path(@task.project_id) %>